import { MonsterDef, VulnType, MonsterTier, Monster } from './types'

export const MONSTER_DEFS: Record<VulnType, MonsterDef> = {
  xss: {
    id: 'xss',
    name: 'XSS Leech',
    form: 'parasitic worm',
    attack: 'Drains HP over time',
    weakness: 'Input sanitization weapons',
    tier: 'rare',
    baseHp: 40,
    baseAttack: 8,
    baseDefense: 3,
    speed: 1.2,
    color: '#ff6b6b',
    brxReward: [15, 50],
  },
  sqli: {
    id: 'sqli',
    name: 'SQLi Hydra',
    form: 'many-headed serpent',
    attack: 'Multi-hit strike',
    weakness: 'Parameterized query weapons',
    tier: 'rare',
    baseHp: 60,
    baseAttack: 12,
    baseDefense: 5,
    speed: 0.8,
    color: '#845ef7',
    brxReward: [20, 60],
  },
  idor: {
    id: 'idor',
    name: 'IDOR Wraith',
    form: 'phasing specter',
    attack: 'Bypasses armor',
    weakness: 'Auth token weapons',
    tier: 'rare',
    baseHp: 35,
    baseAttack: 10,
    baseDefense: 2,
    speed: 1.5,
    color: '#339af0',
    brxReward: [15, 50],
  },
  open_redirect: {
    id: 'open_redirect',
    name: 'Open Redirect Viper',
    form: 'fast striking snake',
    attack: 'High speed, blindsides',
    weakness: 'Validation shield weapons',
    tier: 'uncommon',
    baseHp: 25,
    baseAttack: 7,
    baseDefense: 2,
    speed: 1.8,
    color: '#20c997',
    brxReward: [5, 15],
  },
  ssrf: {
    id: 'ssrf',
    name: 'SSRF Phantom',
    form: 'internal attacker',
    attack: 'Internal damage, ignores armor',
    weakness: 'Network segmentation weapons',
    tier: 'epic',
    baseHp: 70,
    baseAttack: 15,
    baseDefense: 8,
    speed: 0.7,
    color: '#cc5de8',
    brxReward: [50, 200],
  },
  rce: {
    id: 'rce',
    name: 'RCE Leviathan',
    form: 'devastating giant',
    attack: 'Massive AOE attacks',
    weakness: 'Patch & update weapons',
    tier: 'legendary',
    baseHp: 120,
    baseAttack: 25,
    baseDefense: 12,
    speed: 0.4,
    color: '#ff3333',
    brxReward: [200, 1000],
  },
  file_upload: {
    id: 'file_upload',
    name: 'File Upload Mimic',
    form: 'disguised treasure chest',
    attack: 'Trap damage, steals loot',
    weakness: 'File validation weapons',
    tier: 'uncommon',
    baseHp: 30,
    baseAttack: 6,
    baseDefense: 4,
    speed: 0.6,
    color: '#fab005',
    brxReward: [5, 20],
  },
  rate_limit: {
    id: 'rate_limit',
    name: 'Rate Limit Zombie',
    form: 'endless horde',
    attack: 'Overwhelming numbers',
    weakness: 'Token bucket weapons',
    tier: 'common',
    baseHp: 15,
    baseAttack: 3,
    baseDefense: 1,
    speed: 1.0,
    color: '#868e96',
    brxReward: [1, 5],
  },
  s3_bucket: {
    id: 's3_bucket',
    name: 'S3 Bucket Golem',
    form: 'armored giant',
    attack: 'High defense, slow',
    weakness: 'Permission scanner weapons',
    tier: 'epic',
    baseHp: 90,
    baseAttack: 10,
    baseDefense: 15,
    speed: 0.3,
    color: '#4c6ef5',
    brxReward: [50, 150],
  },
  xxe: {
    id: 'xxe',
    name: 'XXE Entity',
    form: 'formless horror',
    attack: 'XML injection, data drain',
    weakness: 'Parser configuration weapons',
    tier: 'epic',
    baseHp: 55,
    baseAttack: 14,
    baseDefense: 6,
    speed: 0.9,
    color: '#be4bdb',
    brxReward: [40, 180],
  },
}

export const MONSTER_TIERS: MonsterTier[] = ['common', 'uncommon', 'rare', 'epic', 'legendary']

export const TIER_COLORS: Record<MonsterTier, string> = {
  common: '#868e96',
  uncommon: '#20c997',
  rare: '#339af0',
  epic: '#cc5de8',
  legendary: '#ff3333',
}

export function spawnMonster(_zone: string): Monster {
  // Select monsters based on zone difficulty
  const defs = Object.values(MONSTER_DEFS)
  const def = defs[Math.floor(Math.random() * defs.length)]

  const tierMult = MONSTER_TIERS.indexOf(def.tier) + 1

  return {
    id: `monster_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
    defId: def.id,
    hp: def.baseHp * tierMult,
    maxHp: def.baseHp * tierMult,
    attack: def.baseAttack * tierMult + Math.floor(Math.random() * 5),
    defense: def.baseDefense * tierMult,
    x: (Math.random() - 0.5) * 20,
    z: (Math.random() - 0.5) * 20,
    tier: def.tier,
    alive: true,
    aggroRange: 5 + Math.random() * 3,
  }
}

export function spawnMonsterWave(count: number, _zone: string): Monster[] {
  return Array.from({ length: count }, () => spawnMonster(_zone))
}
