import { WeaponDef, WeaponRarity } from './types'

const upgradeCost = (base: number) => (level: number) => Math.floor(base * Math.pow(1.5, level))

export const WEAPONS: WeaponDef[] = [
  // ─── Common ──────────────────────────────────────────────────
  {
    id: 'gau',
    name: 'GAU Scanner',
    realTool: 'gau',
    category: 'scanner',
    rarity: 'common',
    baseDamage: 8,
    critChance: 0.05,
    specialEffect: 'None',
    price: 0, // Starting weapon
    upgrades: 0,
    maxUpgrades: 5,
    upgradeCost: upgradeCost(50),
  },
  {
    id: 'httpx',
    name: 'HTTPX Probe',
    realTool: 'httpx',
    category: 'scanner',
    rarity: 'common',
    baseDamage: 10,
    critChance: 0.05,
    specialEffect: 'None',
    price: 100,
    upgrades: 0,
    maxUpgrades: 5,
    upgradeCost: upgradeCost(50),
  },
  {
    id: 'dirsearch',
    name: 'Dirsearch Blade',
    realTool: 'dirsearch',
    category: 'fuzzer',
    rarity: 'common',
    baseDamage: 9,
    critChance: 0.08,
    specialEffect: 'None',
    price: 120,
    upgrades: 0,
    maxUpgrades: 5,
    upgradeCost: upgradeCost(50),
  },

  // ─── Uncommon ────────────────────────────────────────────────
  {
    id: 'ffuf',
    name: 'FFUF Rapid Fire',
    realTool: 'ffuf',
    category: 'fuzzer',
    rarity: 'uncommon',
    baseDamage: 15,
    critChance: 0.1,
    specialEffect: '+25% attack speed',
    price: 300,
    upgrades: 0,
    maxUpgrades: 5,
    upgradeCost: upgradeCost(100),
  },
  {
    id: 'nmap',
    name: 'NMAP Recon Cannon',
    realTool: 'nmap',
    category: 'scanner',
    rarity: 'uncommon',
    baseDamage: 12,
    critChance: 0.08,
    specialEffect: 'Reveals hidden monsters',
    price: 350,
    upgrades: 0,
    maxUpgrades: 5,
    upgradeCost: upgradeCost(100),
  },

  // ─── Rare ────────────────────────────────────────────────────
  {
    id: 'nuclei',
    name: 'Nuclei Heavy Cannon',
    realTool: 'nuclei',
    category: 'exploit_kit',
    rarity: 'rare',
    baseDamage: 25,
    critChance: 0.15,
    specialEffect: '3x damage to known CVEs',
    price: 800,
    upgrades: 0,
    maxUpgrades: 7,
    upgradeCost: upgradeCost(200),
  },
  {
    id: 'sqlmap',
    name: 'SQLMap Injector',
    realTool: 'sqlmap',
    category: 'payload_tool',
    rarity: 'rare',
    baseDamage: 22,
    critChance: 0.12,
    specialEffect: '2x damage to SQLi monsters',
    price: 750,
    upgrades: 0,
    maxUpgrades: 7,
    upgradeCost: upgradeCost(200),
  },
  {
    id: 'dalfox',
    name: 'DalFox XSS Cannon',
    realTool: 'dalfox',
    category: 'payload_tool',
    rarity: 'rare',
    baseDamage: 20,
    critChance: 0.18,
    specialEffect: '2x damage to XSS monsters',
    price: 700,
    upgrades: 0,
    maxUpgrades: 7,
    upgradeCost: upgradeCost(200),
  },

  // ─── Epic ────────────────────────────────────────────────────
  {
    id: 'burpsuite',
    name: 'Burp Suite Interceptor',
    realTool: 'Burp Suite',
    category: 'proxy',
    rarity: 'epic',
    baseDamage: 35,
    critChance: 0.2,
    specialEffect: 'Intercept and redirect enemy attacks (20% chance)',
    price: 2000,
    upgrades: 0,
    maxUpgrades: 7,
    upgradeCost: upgradeCost(400),
  },
  {
    id: 'metasploit',
    name: 'Metasploit Framework',
    realTool: 'Metasploit',
    category: 'exploit_kit',
    rarity: 'epic',
    baseDamage: 40,
    critChance: 0.25,
    specialEffect: 'Execute monsters below 20% HP instantly',
    price: 2500,
    upgrades: 0,
    maxUpgrades: 7,
    upgradeCost: upgradeCost(400),
  },
  {
    id: 'cloud_enum',
    name: 'Cloud Enumerator',
    realTool: 'cloud_enum',
    category: 'cloud_tool',
    rarity: 'epic',
    baseDamage: 30,
    critChance: 0.15,
    specialEffect: '3x damage to cloud-type monsters',
    price: 2200,
    upgrades: 0,
    maxUpgrades: 7,
    upgradeCost: upgradeCost(400),
  },

  // ─── Legendary ───────────────────────────────────────────────
  {
    id: 'cve_hammer',
    name: 'CVE Hammer of Justice',
    realTool: 'Nuclei + Metasploit',
    category: 'exploit_kit',
    rarity: 'legendary',
    baseDamage: 60,
    critChance: 0.35,
    specialEffect: '40% crit, AOE damage, 10% lifesteal',
    price: 10000,
    upgrades: 0,
    maxUpgrades: 10,
    upgradeCost: upgradeCost(1000),
  },
  {
    id: 'zero_day',
    name: 'Zero-Day Injector',
    realTool: 'Custom exploit',
    category: 'payload_tool',
    rarity: 'legendary',
    baseDamage: 75,
    critChance: 0.4,
    specialEffect: 'Ignores armor, 50% crit damage bonus',
    price: 15000,
    upgrades: 0,
    maxUpgrades: 10,
    upgradeCost: upgradeCost(1000),
  },
]

export const WEAPONS_BY_RARITY: Record<WeaponRarity, WeaponDef[]> = {
  common: WEAPONS.filter(w => w.rarity === 'common'),
  uncommon: WEAPONS.filter(w => w.rarity === 'uncommon'),
  rare: WEAPONS.filter(w => w.rarity === 'rare'),
  epic: WEAPONS.filter(w => w.rarity === 'epic'),
  legendary: WEAPONS.filter(w => w.rarity === 'legendary'),
}

export function getWeapon(id: string): WeaponDef | undefined {
  return WEAPONS.find(w => w.id === id)
}
